export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_START = 'GET_EMPLOYEES_START';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAIL = 'GET_EMPLOYEES_FAIL';

export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BY_ID';
export const GET_EMPLOYEE_BY_ID_START = 'GET_EMPLOYEE_BY_ID_START';
export const GET_EMPLOYEE_BY_ID_SUCCESS = 'GET_EMPLOYEE_BY_ID_SUCCESS';
export const GET_EMPLOYEE_BY_ID_FAIL = 'GET_EMPLOYEE_BY_ID_FAIL';